embeddings {
  tensor_name: "query_embeddings"
  tensor_path: "query_embeddings.tsv"
  metadata_path: "query_metadata.tsv"
}
embeddings {
  tensor_name: "domain_centroids"
  tensor_path: "domain_centroids.tsv"
  metadata_path: "domain_metadata.tsv"
}
